<a href="https://colab.research.google.com/github/Dileep2896/Machine-Learning/blob/main/Natural_Language_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Natural Language Processing Using the Naive Bayes

## Importing the libraries

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the datasets

In [10]:
dataset = pd.read_csv("Restaurant_Reviews.tsv", delimiter="\t", quoting = 3)

In [11]:
dataset[:10]

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1
5     Now I am getting angry and I want my damn pho.      0
6              Honeslty it didn't taste THAT fresh.)      0
7  The potatoes were like rubber and you could te...      0
8                          The fries were great too.      1
9                                     A great touch.      1

## Cleaning the texts

In [14]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 1000):
  review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  allStopWords = stopwords.words('english')
  allStopWords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(allStopWords)]
  review = " ".join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [15]:
corpus[:10]

['wow love place',
 'crust not good',
 'not tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch']

## Creating the Bag of Words model (Tokentisation)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

In [21]:
X[:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
y[:10]

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [23]:
len(X[0])

1500

## Splitting the datasets into training set and test sets

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [25]:
len(X_train)

800

In [26]:
len(X_test)

200

## Training the Naive Bayes model using the training set

In [27]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Predicting the test set results

In [28]:
y_pred = classifier.predict(X_test)
y_pred[:10]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1])

In [29]:
y_test[:10]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

## Making the confusion matrix

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test,
                 y_pred),
accuracy_score(y_test,
               y_pred))

[[55 42]
 [12 91]] 0.73
